import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../../component/layouts/Layout'
import styles from '../styles/Home.module.css'

const AddUserPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>User add</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </>
  )
}

export default AddUserPage
