import { Button } from '@material-tailwind/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { BasicTable } from '../../component/base/BasicTable'
import Layout from '../../component/layouts/Layout'
import { ColumnsProps } from '../../shared/interface/table.interface'
import styles from '../styles/Home.module.css'

function createData(
    name: string,
    calories: number,
    fat: number,
    carbs: number,
    protein: number,
) {
    return { name, calories, fat, carbs, protein };
}

const rows = [
    createData('Frozen yoghurt', 159, 6.0, 24, 4.0),
    createData('Ice cream sandwich', 237, 9.0, 37, 4.3),
    createData('Eclair', 262, 16.0, 24, 6.0),
    createData('Cupcake', 305, 3.7, 67, 4.3),
    createData('Gingerbread', 356, 16.0, 49, 3.9),
];

const conlumns: ColumnsProps[] = [
    {
        dataIndex: 'name',
        label: 'Name',
    },
    {
        dataIndex: 'calories',
        label: 'Calories',
    },
    {
        dataIndex: 'fat',
        label: 'Fat',
    },
    {
        dataIndex: 'carbs',
        label: 'Carbs',
    },
    {
        dataIndex: 'protein',
        label: 'Protein',
    },
]


const IndexPage: NextPage = () => (
    <>
        <Head>
            <title>User</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
            <BasicTable dataSource={rows} columns={conlumns} />
        </Layout>
    </>
)

export default IndexPage
